#!/usr/bin/env python3

from pizza import random_pizza, findClosestPizza
import sys

# Creata a random pizza, and send along the command line arguments
pizza = random_pizza(sys.argv)
instruktioner = findClosestPizza(pizza)

print("Namn: " + pizza.name + "\n")

for i in pizza.get_ingredients():
    print(i)

print(instruktioner)

