#!/usr/bin/env python

from pizza import random_pizza
import sys

# Creata a random pizza, and send along the command line arguments
pizza = random_pizza(sys.argv)

print("Namn: " + pizza.name + "\n")

for i in pizza.get_ingredients():
    print(i)
